-- ---------------------------------------------------------------------------
-- Core configuration schema.
--
-- Everything that describes *what* to monitor lives here. Collected values live
-- in the history and trend tables created by V2, which are partitioned on time
-- and have a very different read/write profile.
--
-- Every configuration table carries tenant_id. The platform is deployed as a
-- hosted service, so isolation has to be enforceable in the data model rather
-- than assumed from the deployment topology.
-- ---------------------------------------------------------------------------

CREATE TABLE tenant (
    tenant_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(128) NOT NULL,
    slug            VARCHAR(64)  NOT NULL,
    status          VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    -- Retention is a per-tenant commercial concern, not a global constant.
    history_retention_days  INTEGER NOT NULL DEFAULT 90,
    trend_retention_days    INTEGER NOT NULL DEFAULT 730,
    max_hosts       INTEGER      NOT NULL DEFAULT 0,  -- 0 = unlimited
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_tenant_slug UNIQUE (slug),
    CONSTRAINT ck_tenant_status CHECK (status IN ('ACTIVE', 'SUSPENDED'))
);

-- ---------------------------------------------------------------------------
-- Users, roles and permissions
-- ---------------------------------------------------------------------------

CREATE TABLE role (
    role_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT       REFERENCES tenant(tenant_id) ON DELETE CASCADE,
    name            VARCHAR(64)  NOT NULL,
    role_type       VARCHAR(16)  NOT NULL,
    -- Named permissions granted to the role, e.g. host.write, action.write.
    permissions     JSONB        NOT NULL DEFAULT '[]'::jsonb,
    builtin         BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_role_name UNIQUE (tenant_id, name),
    CONSTRAINT ck_role_type CHECK (role_type IN ('USER', 'ADMIN', 'SUPER_ADMIN', 'GUEST'))
);

CREATE TABLE app_user (
    user_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT       NOT NULL REFERENCES tenant(tenant_id) ON DELETE CASCADE,
    username        VARCHAR(128) NOT NULL,
    password_hash   VARCHAR(255),
    full_name       VARCHAR(128),
    email           VARCHAR(255),
    role_id         BIGINT       REFERENCES role(role_id) ON DELETE SET NULL,
    timezone        VARCHAR(64)  NOT NULL DEFAULT 'UTC',
    lang            VARCHAR(16)  NOT NULL DEFAULT 'en',
    theme           VARCHAR(16)  NOT NULL DEFAULT 'dark',
    -- Auth source: LOCAL uses password_hash, the rest delegate to an IdP.
    auth_source     VARCHAR(16)  NOT NULL DEFAULT 'LOCAL',
    external_id     VARCHAR(255),
    mfa_secret      VARCHAR(128),
    mfa_enabled     BOOLEAN      NOT NULL DEFAULT FALSE,
    enabled         BOOLEAN      NOT NULL DEFAULT TRUE,
    failed_logins   INTEGER      NOT NULL DEFAULT 0,
    locked_until    TIMESTAMPTZ,
    last_login_at   TIMESTAMPTZ,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_user_username UNIQUE (tenant_id, username),
    CONSTRAINT ck_user_auth_source CHECK (auth_source IN ('LOCAL', 'LDAP', 'SAML', 'OIDC'))
);

CREATE TABLE user_group (
    usrgrp_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT       NOT NULL REFERENCES tenant(tenant_id) ON DELETE CASCADE,
    name            VARCHAR(128) NOT NULL,
    -- When a user is in a disabled group they cannot log in, regardless of
    -- their own enabled flag. Matches operator expectations from Zabbix.
    enabled         BOOLEAN      NOT NULL DEFAULT TRUE,
    debug_mode      BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_usrgrp_name UNIQUE (tenant_id, name)
);

CREATE TABLE user_group_member (
    usrgrp_id       BIGINT NOT NULL REFERENCES user_group(usrgrp_id) ON DELETE CASCADE,
    user_id         BIGINT NOT NULL REFERENCES app_user(user_id) ON DELETE CASCADE,
    PRIMARY KEY (usrgrp_id, user_id)
);

-- ---------------------------------------------------------------------------
-- Proxies: on-premise collectors that reach networks the cloud server cannot
-- ---------------------------------------------------------------------------

CREATE TABLE proxy (
    proxy_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT       NOT NULL REFERENCES tenant(tenant_id) ON DELETE CASCADE,
    name            VARCHAR(128) NOT NULL,
    description     TEXT         NOT NULL DEFAULT '',
    -- ACTIVE: the proxy dials out to us (the only mode that works behind NAT).
    -- PASSIVE: we dial the proxy, for on-prem installs of the whole platform.
    mode            VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    address         VARCHAR(255),
    port            INTEGER      NOT NULL DEFAULT 10151,
    -- Bcrypt hash of the enrolment token; the plaintext is shown once at
    -- creation and never stored.
    token_hash      VARCHAR(255),
    token_prefix    VARCHAR(16),
    tls_accept      VARCHAR(16)  NOT NULL DEFAULT 'TOKEN',
    config_revision BIGINT       NOT NULL DEFAULT 1,
    last_seen_at    TIMESTAMPTZ,
    last_config_at  TIMESTAMPTZ,
    version         VARCHAR(32),
    queue_depth     INTEGER      NOT NULL DEFAULT 0,
    clock_skew_ms   BIGINT       NOT NULL DEFAULT 0,
    enabled         BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_proxy_name UNIQUE (tenant_id, name),
    CONSTRAINT ck_proxy_mode CHECK (mode IN ('ACTIVE', 'PASSIVE')),
    CONSTRAINT ck_proxy_tls CHECK (tls_accept IN ('NONE', 'TOKEN', 'CERT'))
);

CREATE INDEX ix_proxy_token_prefix ON proxy (token_prefix);

-- ---------------------------------------------------------------------------
-- Host groups, hosts, templates and interfaces
-- ---------------------------------------------------------------------------

CREATE TABLE host_group (
    group_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT       NOT NULL REFERENCES tenant(tenant_id) ON DELETE CASCADE,
    name            VARCHAR(255) NOT NULL,
    description     TEXT         NOT NULL DEFAULT '',
    CONSTRAINT uq_host_group_name UNIQUE (tenant_id, name)
);

-- Hosts, templates and discovered host prototypes share one table because
-- templates are structurally hosts that are never polled. Keeping them
-- together is what makes "link a template" a pure reference operation.
CREATE TABLE host (
    host_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT       NOT NULL REFERENCES tenant(tenant_id) ON DELETE CASCADE,
    host            VARCHAR(255) NOT NULL,          -- technical name, used in keys
    name            VARCHAR(255) NOT NULL,          -- visible name
    flags           VARCHAR(16)  NOT NULL DEFAULT 'MONITORED',
    -- Broad classification drives default templates and UI grouping. Cameras
    -- are called out because their health model differs from a server's.
    host_class      VARCHAR(24)  NOT NULL DEFAULT 'GENERIC',
    description     TEXT         NOT NULL DEFAULT '',
    status          VARCHAR(16)  NOT NULL DEFAULT 'ENABLED',
    proxy_id        BIGINT       REFERENCES proxy(proxy_id) ON DELETE SET NULL,
    -- Availability per interface type, maintained by the pollers.
    ipmi_username   VARCHAR(64),
    ipmi_password   VARCHAR(255),
    -- Inventory is free-form but indexed; operators search it constantly.
    inventory_mode  VARCHAR(16)  NOT NULL DEFAULT 'MANUAL',
    inventory       JSONB        NOT NULL DEFAULT '{}'::jsonb,
    maintenance_status VARCHAR(16) NOT NULL DEFAULT 'NONE',
    maintenance_from   TIMESTAMPTZ,
    -- Set when this host was created by a discovery rule, so we know it may
    -- also be removed automatically.
    discovered_by_rule_id BIGINT,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_host_technical UNIQUE (tenant_id, host),
    CONSTRAINT ck_host_flags CHECK (flags IN ('MONITORED', 'TEMPLATE', 'PROTOTYPE')),
    CONSTRAINT ck_host_status CHECK (status IN ('ENABLED', 'DISABLED')),
    CONSTRAINT ck_host_class CHECK (host_class IN
        ('GENERIC', 'SERVER', 'NETWORK_DEVICE', 'CAMERA', 'PRINTER', 'UPS',
         'STORAGE', 'HYPERVISOR', 'APPLICATION', 'CLOUD')),
    CONSTRAINT ck_host_inventory_mode CHECK (inventory_mode IN ('DISABLED', 'MANUAL', 'AUTOMATIC')),
    CONSTRAINT ck_host_maintenance CHECK (maintenance_status IN ('NONE', 'IN_PROGRESS'))
);

CREATE INDEX ix_host_tenant_status ON host (tenant_id, status) WHERE flags = 'MONITORED';
CREATE INDEX ix_host_proxy ON host (proxy_id) WHERE proxy_id IS NOT NULL;
CREATE INDEX ix_host_class ON host (tenant_id, host_class);

CREATE TABLE host_group_member (
    host_id         BIGINT NOT NULL REFERENCES host(host_id) ON DELETE CASCADE,
    group_id        BIGINT NOT NULL REFERENCES host_group(group_id) ON DELETE CASCADE,
    PRIMARY KEY (host_id, group_id)
);

CREATE INDEX ix_host_group_member_group ON host_group_member (group_id);

-- Template linkage. A host may link many templates; templates may nest.
CREATE TABLE host_template (
    host_id         BIGINT NOT NULL REFERENCES host(host_id) ON DELETE CASCADE,
    template_id     BIGINT NOT NULL REFERENCES host(host_id) ON DELETE CASCADE,
    PRIMARY KEY (host_id, template_id),
    CONSTRAINT ck_host_template_distinct CHECK (host_id <> template_id)
);

CREATE INDEX ix_host_template_template ON host_template (template_id);

CREATE TABLE host_interface (
    interface_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host_id         BIGINT       NOT NULL REFERENCES host(host_id) ON DELETE CASCADE,
    type            VARCHAR(16)  NOT NULL,
    -- Exactly one interface per type is the default for its type; items that
    -- do not name an interface bind to it.
    main            BOOLEAN      NOT NULL DEFAULT TRUE,
    use_ip          BOOLEAN      NOT NULL DEFAULT TRUE,
    ip              VARCHAR(64),
    dns             VARCHAR(255),
    port            INTEGER      NOT NULL,
    -- SNMP specifics live here rather than on the item: they are a property of
    -- how you reach the device, not of what you ask it.
    snmp_version    VARCHAR(8),
    snmp_community  VARCHAR(255),
    snmp_v3_security_name     VARCHAR(128),
    snmp_v3_security_level    VARCHAR(24),
    snmp_v3_auth_protocol     VARCHAR(16),
    snmp_v3_auth_passphrase   VARCHAR(255),
    snmp_v3_priv_protocol     VARCHAR(16),
    snmp_v3_priv_passphrase   VARCHAR(255),
    snmp_v3_context_name      VARCHAR(128),
    snmp_max_repetitions      INTEGER NOT NULL DEFAULT 10,
    snmp_bulk       BOOLEAN      NOT NULL DEFAULT TRUE,
    -- Availability tracked per interface: a camera can answer ping while its
    -- RTSP endpoint is dead, and operators need to see that difference.
    available       VARCHAR(16)  NOT NULL DEFAULT 'UNKNOWN',
    error           TEXT         NOT NULL DEFAULT '',
    errors_from     TIMESTAMPTZ,
    disable_until   TIMESTAMPTZ,
    CONSTRAINT ck_interface_type CHECK (type IN ('AGENT', 'SNMP', 'IPMI', 'JMX', 'HTTP', 'RTSP', 'ONVIF')),
    CONSTRAINT ck_interface_available CHECK (available IN ('UNKNOWN', 'AVAILABLE', 'UNAVAILABLE')),
    CONSTRAINT ck_interface_snmp_version CHECK (snmp_version IS NULL OR snmp_version IN ('V1', 'V2C', 'V3')),
    CONSTRAINT ck_interface_addr CHECK (
        (use_ip AND ip IS NOT NULL AND ip <> '') OR
        (NOT use_ip AND dns IS NOT NULL AND dns <> ''))
);

CREATE INDEX ix_interface_host ON host_interface (host_id);
-- Only one main interface may exist per host per type.
CREATE UNIQUE INDEX uq_interface_main ON host_interface (host_id, type) WHERE main;

-- ---------------------------------------------------------------------------
-- Macros: user-defined substitution variables, {$NAME} style
-- ---------------------------------------------------------------------------

CREATE TABLE global_macro (
    macro_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT       NOT NULL REFERENCES tenant(tenant_id) ON DELETE CASCADE,
    macro           VARCHAR(255) NOT NULL,
    value           TEXT         NOT NULL DEFAULT '',
    -- SECRET values are never returned by the API and are encrypted at rest.
    type            VARCHAR(16)  NOT NULL DEFAULT 'TEXT',
    description     TEXT         NOT NULL DEFAULT '',
    CONSTRAINT uq_global_macro UNIQUE (tenant_id, macro),
    CONSTRAINT ck_global_macro_type CHECK (type IN ('TEXT', 'SECRET', 'VAULT'))
);

CREATE TABLE host_macro (
    hostmacro_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host_id         BIGINT       NOT NULL REFERENCES host(host_id) ON DELETE CASCADE,
    macro           VARCHAR(255) NOT NULL,
    value           TEXT         NOT NULL DEFAULT '',
    type            VARCHAR(16)  NOT NULL DEFAULT 'TEXT',
    description     TEXT         NOT NULL DEFAULT '',
    CONSTRAINT uq_host_macro UNIQUE (host_id, macro),
    CONSTRAINT ck_host_macro_type CHECK (type IN ('TEXT', 'SECRET', 'VAULT'))
);

-- ---------------------------------------------------------------------------
-- Value maps: render raw numbers as operator-readable text (1 => Up)
-- ---------------------------------------------------------------------------

CREATE TABLE value_map (
    valuemap_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT       NOT NULL REFERENCES tenant(tenant_id) ON DELETE CASCADE,
    host_id         BIGINT       REFERENCES host(host_id) ON DELETE CASCADE,
    name            VARCHAR(128) NOT NULL
);

CREATE TABLE value_map_mapping (
    mapping_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valuemap_id     BIGINT       NOT NULL REFERENCES value_map(valuemap_id) ON DELETE CASCADE,
    match_type      VARCHAR(16)  NOT NULL DEFAULT 'EQUAL',
    value           VARCHAR(255) NOT NULL DEFAULT '',
    newvalue        VARCHAR(255) NOT NULL,
    sortorder       INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT ck_mapping_type CHECK (match_type IN
        ('EQUAL', 'GREATER_OR_EQUAL', 'LESS_OR_EQUAL', 'IN_RANGE', 'REGEXP', 'DEFAULT'))
);

-- ---------------------------------------------------------------------------
-- Items: the individual metrics collected from a host
-- ---------------------------------------------------------------------------

CREATE TABLE item (
    item_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT       NOT NULL REFERENCES tenant(tenant_id) ON DELETE CASCADE,
    host_id         BIGINT       NOT NULL REFERENCES host(host_id) ON DELETE CASCADE,
    interface_id    BIGINT       REFERENCES host_interface(interface_id) ON DELETE SET NULL,
    name            VARCHAR(255) NOT NULL,
    key_            VARCHAR(2048) NOT NULL,
    check_type      VARCHAR(32)  NOT NULL,
    value_type      VARCHAR(16)  NOT NULL,
    units           VARCHAR(32)  NOT NULL DEFAULT '',
    -- Update interval in seconds; 0 means the item runs only on its custom
    -- scheduling intervals.
    delay_seconds   INTEGER      NOT NULL DEFAULT 60,
    -- Flexible and scheduled intervals, e.g. "50/1-5,09:00-18:00" or "h/30".
    custom_intervals JSONB       NOT NULL DEFAULT '[]'::jsonb,
    history_days    INTEGER      NOT NULL DEFAULT 31,
    trend_days      INTEGER      NOT NULL DEFAULT 365,
    status          VARCHAR(16)  NOT NULL DEFAULT 'ENABLED',
    state           VARCHAR(16)  NOT NULL DEFAULT 'NORMAL',
    error           TEXT         NOT NULL DEFAULT '',
    valuemap_id     BIGINT       REFERENCES value_map(valuemap_id) ON DELETE SET NULL,
    description     TEXT         NOT NULL DEFAULT '',
    -- Check-type specific configuration: SNMP OID, HTTP URL and headers, RTSP
    -- path, script body, JMX object name, calculated formula, and so on.
    params          JSONB        NOT NULL DEFAULT '{}'::jsonb,
    timeout_seconds INTEGER      NOT NULL DEFAULT 3,
    -- Set for items produced by low-level discovery, pointing at the prototype
    -- they came from, so they can be pruned when the entity disappears.
    template_item_id BIGINT      REFERENCES item(item_id) ON DELETE SET NULL,
    discovered_by_rule_id BIGINT,
    lld_macro_values JSONB       NOT NULL DEFAULT '{}'::jsonb,
    flags           VARCHAR(16)  NOT NULL DEFAULT 'NORMAL',
    -- Scheduling state, updated by the poller.
    next_check_at   TIMESTAMPTZ,
    last_check_at   TIMESTAMPTZ,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_item_key UNIQUE (host_id, key_),
    CONSTRAINT ck_item_status CHECK (status IN ('ENABLED', 'DISABLED')),
    CONSTRAINT ck_item_state CHECK (state IN ('NORMAL', 'NOT_SUPPORTED')),
    CONSTRAINT ck_item_flags CHECK (flags IN ('NORMAL', 'DISCOVERY_RULE', 'PROTOTYPE', 'DISCOVERED')),
    CONSTRAINT ck_item_value_type CHECK (value_type IN ('UNSIGNED', 'FLOAT', 'CHARACTER', 'LOG', 'TEXT')),
    CONSTRAINT ck_item_delay CHECK (delay_seconds >= 0)
);

-- The scheduler's hot query: "which enabled items are due?"
CREATE INDEX ix_item_due ON item (next_check_at)
    WHERE status = 'ENABLED' AND flags IN ('NORMAL', 'DISCOVERED', 'DISCOVERY_RULE');
CREATE INDEX ix_item_host ON item (host_id);
CREATE INDEX ix_item_template ON item (template_item_id) WHERE template_item_id IS NOT NULL;
CREATE INDEX ix_item_check_type ON item (tenant_id, check_type);

-- Ordered transformation pipeline applied to a raw value before storage.
CREATE TABLE item_preprocessing (
    preproc_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id         BIGINT       NOT NULL REFERENCES item(item_id) ON DELETE CASCADE,
    step            INTEGER      NOT NULL,
    type            VARCHAR(32)  NOT NULL,
    params          JSONB        NOT NULL DEFAULT '[]'::jsonb,
    -- What to do when this step fails: fail the item, discard the value, set a
    -- fixed value, or set an error message.
    error_handler   VARCHAR(24)  NOT NULL DEFAULT 'ERROR',
    error_handler_params TEXT    NOT NULL DEFAULT '',
    CONSTRAINT uq_preproc_step UNIQUE (item_id, step),
    CONSTRAINT ck_preproc_error_handler CHECK (error_handler IN
        ('ERROR', 'DISCARD_VALUE', 'SET_VALUE', 'SET_ERROR'))
);

-- ---------------------------------------------------------------------------
-- Tags: the primary way problems are filtered, routed and correlated
-- ---------------------------------------------------------------------------

CREATE TABLE host_tag (
    tag_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host_id         BIGINT       NOT NULL REFERENCES host(host_id) ON DELETE CASCADE,
    tag             VARCHAR(255) NOT NULL,
    value           VARCHAR(255) NOT NULL DEFAULT '',
    CONSTRAINT uq_host_tag UNIQUE (host_id, tag, value)
);

CREATE INDEX ix_host_tag_lookup ON host_tag (tag, value);

CREATE TABLE item_tag (
    tag_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id         BIGINT       NOT NULL REFERENCES item(item_id) ON DELETE CASCADE,
    tag             VARCHAR(255) NOT NULL,
    value           VARCHAR(255) NOT NULL DEFAULT '',
    CONSTRAINT uq_item_tag UNIQUE (item_id, tag, value)
);

-- ---------------------------------------------------------------------------
-- Triggers: boolean expressions over collected values that define a problem
-- ---------------------------------------------------------------------------

CREATE TABLE trigger_def (
    trigger_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT       NOT NULL REFERENCES tenant(tenant_id) ON DELETE CASCADE,
    host_id         BIGINT       NOT NULL REFERENCES host(host_id) ON DELETE CASCADE,
    description     VARCHAR(1024) NOT NULL,
    expression      TEXT         NOT NULL,
    -- When set, the problem stays open until this expression is true, rather
    -- than until the problem expression goes false. This is what implements
    -- hysteresis and stops alert flapping on a threshold boundary.
    recovery_mode   VARCHAR(24)  NOT NULL DEFAULT 'EXPRESSION',
    recovery_expression TEXT     NOT NULL DEFAULT '',
    severity        VARCHAR(24)  NOT NULL DEFAULT 'NOT_CLASSIFIED',
    status          VARCHAR(16)  NOT NULL DEFAULT 'ENABLED',
    state           VARCHAR(16)  NOT NULL DEFAULT 'NORMAL',
    value           VARCHAR(16)  NOT NULL DEFAULT 'OK',
    error           TEXT         NOT NULL DEFAULT '',
    -- OK events can be generated for every recovery or only for the matching
    -- problem event, which matters when several problems share a trigger.
    correlation_mode VARCHAR(24) NOT NULL DEFAULT 'ALL',
    correlation_tag VARCHAR(255) NOT NULL DEFAULT '',
    -- MULTIPLE lets one trigger hold several simultaneous problems, keyed by
    -- the event name; needed for log and trap driven triggers.
    event_generation VARCHAR(16) NOT NULL DEFAULT 'SINGLE',
    manual_close    BOOLEAN      NOT NULL DEFAULT FALSE,
    url             VARCHAR(2048) NOT NULL DEFAULT '',
    comments        TEXT         NOT NULL DEFAULT '',
    opdata          VARCHAR(1024) NOT NULL DEFAULT '',
    event_name      VARCHAR(1024) NOT NULL DEFAULT '',
    template_trigger_id BIGINT   REFERENCES trigger_def(trigger_id) ON DELETE SET NULL,
    discovered_by_rule_id BIGINT,
    flags           VARCHAR(16)  NOT NULL DEFAULT 'NORMAL',
    last_change_at  TIMESTAMPTZ,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_trigger_severity CHECK (severity IN
        ('NOT_CLASSIFIED', 'INFORMATION', 'WARNING', 'AVERAGE', 'HIGH', 'DISASTER')),
    CONSTRAINT ck_trigger_status CHECK (status IN ('ENABLED', 'DISABLED')),
    CONSTRAINT ck_trigger_state CHECK (state IN ('NORMAL', 'UNKNOWN')),
    CONSTRAINT ck_trigger_value CHECK (value IN ('OK', 'PROBLEM')),
    CONSTRAINT ck_trigger_recovery_mode CHECK (recovery_mode IN
        ('EXPRESSION', 'RECOVERY_EXPRESSION', 'NONE')),
    CONSTRAINT ck_trigger_event_generation CHECK (event_generation IN ('SINGLE', 'MULTIPLE')),
    CONSTRAINT ck_trigger_flags CHECK (flags IN ('NORMAL', 'PROTOTYPE', 'DISCOVERED'))
);

CREATE INDEX ix_trigger_host ON trigger_def (host_id);
CREATE INDEX ix_trigger_status ON trigger_def (tenant_id, status) WHERE status = 'ENABLED';

-- Which items a trigger reads. Maintained by the expression parser so that a
-- new value can find the triggers it must re-evaluate without a table scan.
CREATE TABLE trigger_item (
    trigger_id      BIGINT NOT NULL REFERENCES trigger_def(trigger_id) ON DELETE CASCADE,
    item_id         BIGINT NOT NULL REFERENCES item(item_id) ON DELETE CASCADE,
    PRIMARY KEY (trigger_id, item_id)
);

CREATE INDEX ix_trigger_item_item ON trigger_item (item_id);

-- A trigger with an unresolved dependency does not fire. This is how "the
-- switch is down" suppresses the forty cameras behind it.
CREATE TABLE trigger_dependency (
    trigger_id      BIGINT NOT NULL REFERENCES trigger_def(trigger_id) ON DELETE CASCADE,
    depends_on_trigger_id BIGINT NOT NULL REFERENCES trigger_def(trigger_id) ON DELETE CASCADE,
    PRIMARY KEY (trigger_id, depends_on_trigger_id),
    CONSTRAINT ck_trigger_dep_distinct CHECK (trigger_id <> depends_on_trigger_id)
);

CREATE TABLE trigger_tag (
    tag_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trigger_id      BIGINT       NOT NULL REFERENCES trigger_def(trigger_id) ON DELETE CASCADE,
    tag             VARCHAR(255) NOT NULL,
    value           VARCHAR(255) NOT NULL DEFAULT '',
    CONSTRAINT uq_trigger_tag UNIQUE (trigger_id, tag, value)
);

-- ---------------------------------------------------------------------------
-- Events and problems
--
-- An event is an immutable fact ("this trigger went to PROBLEM at 09:14").
-- A problem is the mutable open-incident view built from events. Separating
-- them is what allows the problem table to stay small and fast while events
-- accumulate for audit.
-- ---------------------------------------------------------------------------

CREATE TABLE event (
    event_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT       NOT NULL REFERENCES tenant(tenant_id) ON DELETE CASCADE,
    source          VARCHAR(24)  NOT NULL DEFAULT 'TRIGGER',
    object_type     VARCHAR(24)  NOT NULL DEFAULT 'TRIGGER',
    object_id       BIGINT       NOT NULL,
    clock           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    value           VARCHAR(16)  NOT NULL,
    severity        VARCHAR(24)  NOT NULL DEFAULT 'NOT_CLASSIFIED',
    name            VARCHAR(2048) NOT NULL DEFAULT '',
    acknowledged    BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT ck_event_source CHECK (source IN
        ('TRIGGER', 'DISCOVERY', 'AUTOREGISTRATION', 'INTERNAL', 'SERVICE')),
    CONSTRAINT ck_event_value CHECK (value IN ('OK', 'PROBLEM'))
);

CREATE INDEX ix_event_clock ON event (tenant_id, clock DESC);
CREATE INDEX ix_event_object ON event (object_type, object_id, clock DESC);

CREATE TABLE problem (
    problem_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT       NOT NULL REFERENCES tenant(tenant_id) ON DELETE CASCADE,
    event_id        BIGINT       NOT NULL REFERENCES event(event_id) ON DELETE CASCADE,
    source          VARCHAR(24)  NOT NULL DEFAULT 'TRIGGER',
    object_type     VARCHAR(24)  NOT NULL DEFAULT 'TRIGGER',
    object_id       BIGINT       NOT NULL,
    host_id         BIGINT       REFERENCES host(host_id) ON DELETE CASCADE,
    clock           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    name            VARCHAR(2048) NOT NULL DEFAULT '',
    severity        VARCHAR(24)  NOT NULL DEFAULT 'NOT_CLASSIFIED',
    -- Severity can be changed by an operator during triage; the original is
    -- kept so reporting is not rewritten by human action.
    original_severity VARCHAR(24) NOT NULL DEFAULT 'NOT_CLASSIFIED',
    acknowledged    BOOLEAN      NOT NULL DEFAULT FALSE,
    suppressed      BOOLEAN      NOT NULL DEFAULT FALSE,
    suppressed_until TIMESTAMPTZ,
    opdata          VARCHAR(1024) NOT NULL DEFAULT '',
    -- Populated on recovery. A row with r_event_id set is a resolved problem
    -- retained for the problem history view.
    r_event_id      BIGINT       REFERENCES event(event_id) ON DELETE SET NULL,
    resolved_at     TIMESTAMPTZ,
    resolved_by     VARCHAR(128),
    CONSTRAINT uq_problem_event UNIQUE (event_id)
);

CREATE INDEX ix_problem_open ON problem (tenant_id, severity, clock DESC) WHERE r_event_id IS NULL;
CREATE INDEX ix_problem_object ON problem (object_type, object_id) WHERE r_event_id IS NULL;
CREATE INDEX ix_problem_host ON problem (host_id) WHERE r_event_id IS NULL;

CREATE TABLE problem_tag (
    tag_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id      BIGINT       NOT NULL REFERENCES problem(problem_id) ON DELETE CASCADE,
    tag             VARCHAR(255) NOT NULL,
    value           VARCHAR(255) NOT NULL DEFAULT ''
);

CREATE INDEX ix_problem_tag_lookup ON problem_tag (tag, value);
CREATE INDEX ix_problem_tag_problem ON problem_tag (problem_id);

-- Operator actions on a problem: acknowledge, comment, close, change severity.
CREATE TABLE problem_ack (
    ack_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id      BIGINT       NOT NULL REFERENCES problem(problem_id) ON DELETE CASCADE,
    user_id         BIGINT       REFERENCES app_user(user_id) ON DELETE SET NULL,
    clock           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    message         TEXT         NOT NULL DEFAULT '',
    -- Bit set of what this action did, kept as explicit columns for clarity.
    action_acknowledge BOOLEAN   NOT NULL DEFAULT FALSE,
    action_unacknowledge BOOLEAN NOT NULL DEFAULT FALSE,
    action_close    BOOLEAN      NOT NULL DEFAULT FALSE,
    action_message  BOOLEAN      NOT NULL DEFAULT FALSE,
    action_severity BOOLEAN      NOT NULL DEFAULT FALSE,
    action_suppress BOOLEAN      NOT NULL DEFAULT FALSE,
    new_severity    VARCHAR(24),
    suppress_until  TIMESTAMPTZ
);

CREATE INDEX ix_problem_ack_problem ON problem_ack (problem_id, clock DESC);
