-- ---------------------------------------------------------------------------
-- Alerting, escalation, discovery, maintenance and presentation.
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- Media types: the channels an alert can be delivered through
-- ---------------------------------------------------------------------------

CREATE TABLE media_type (
    media_type_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT       NOT NULL REFERENCES tenant(tenant_id) ON DELETE CASCADE,
    name            VARCHAR(128) NOT NULL,
    type            VARCHAR(24)  NOT NULL,
    status          VARCHAR(16)  NOT NULL DEFAULT 'ENABLED',
    -- Channel configuration: SMTP host/port/credentials, webhook URL and
    -- headers, script path, and so on.
    config          JSONB        NOT NULL DEFAULT '{}'::jsonb,
    -- Per-channel message bodies keyed by event source and recovery phase,
    -- e.g. {"TRIGGER.PROBLEM": {"subject": "...", "body": "..."}}.
    templates       JSONB        NOT NULL DEFAULT '{}'::jsonb,
    -- Delivery throttling, so a storm cannot exhaust an SMTP relay or hit a
    -- provider rate limit.
    max_sessions    INTEGER      NOT NULL DEFAULT 1,
    max_attempts    INTEGER      NOT NULL DEFAULT 3,
    attempt_interval_seconds INTEGER NOT NULL DEFAULT 10,
    timeout_seconds INTEGER      NOT NULL DEFAULT 30,
    description     TEXT         NOT NULL DEFAULT '',
    CONSTRAINT uq_media_type_name UNIQUE (tenant_id, name),
    CONSTRAINT ck_media_type_type CHECK (type IN
        ('EMAIL', 'SLACK', 'WEBHOOK', 'SCRIPT', 'SMS', 'TEAMS', 'PAGERDUTY', 'OPSGENIE', 'TELEGRAM')),
    CONSTRAINT ck_media_type_status CHECK (status IN ('ENABLED', 'DISABLED')),
    CONSTRAINT ck_media_type_sessions CHECK (max_sessions BETWEEN 1 AND 100)
);

-- A user's address on a channel, plus when they are willing to be paged.
CREATE TABLE user_media (
    user_media_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL REFERENCES app_user(user_id) ON DELETE CASCADE,
    media_type_id   BIGINT       NOT NULL REFERENCES media_type(media_type_id) ON DELETE CASCADE,
    send_to         VARCHAR(1024) NOT NULL,
    -- Time periods this user accepts alerts, e.g. "1-5,09:00-18:00".
    active_period   VARCHAR(255) NOT NULL DEFAULT '1-7,00:00-24:00',
    -- Minimum severity delivered on this channel: SMS for DISASTER only,
    -- email for everything.
    severity_filter VARCHAR(24)  NOT NULL DEFAULT 'NOT_CLASSIFIED',
    enabled         BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE INDEX ix_user_media_user ON user_media (user_id);

-- ---------------------------------------------------------------------------
-- Actions: what to do when an event matches a set of conditions
-- ---------------------------------------------------------------------------

CREATE TABLE action (
    action_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT       NOT NULL REFERENCES tenant(tenant_id) ON DELETE CASCADE,
    name            VARCHAR(255) NOT NULL,
    event_source    VARCHAR(24)  NOT NULL DEFAULT 'TRIGGER',
    status          VARCHAR(16)  NOT NULL DEFAULT 'ENABLED',
    -- How the condition list combines: all, any, or a custom boolean formula
    -- over condition labels such as "A and (B or C)".
    eval_type       VARCHAR(16)  NOT NULL DEFAULT 'AND_OR',
    formula         VARCHAR(1024) NOT NULL DEFAULT '',
    -- Seconds between escalation steps.
    escalation_period_seconds INTEGER NOT NULL DEFAULT 3600,
    -- Pause escalation while the host is in a maintenance window, rather than
    -- discarding the alert outright.
    pause_during_maintenance BOOLEAN NOT NULL DEFAULT TRUE,
    -- Stop escalating once someone acknowledges. Without this, escalation
    -- keeps waking people who already know.
    pause_on_acknowledge BOOLEAN NOT NULL DEFAULT TRUE,
    notify_on_recovery BOOLEAN   NOT NULL DEFAULT TRUE,
    notify_on_update BOOLEAN     NOT NULL DEFAULT FALSE,
    description     TEXT         NOT NULL DEFAULT '',
    CONSTRAINT uq_action_name UNIQUE (tenant_id, name),
    CONSTRAINT ck_action_source CHECK (event_source IN
        ('TRIGGER', 'DISCOVERY', 'AUTOREGISTRATION', 'INTERNAL', 'SERVICE')),
    CONSTRAINT ck_action_status CHECK (status IN ('ENABLED', 'DISABLED')),
    CONSTRAINT ck_action_eval CHECK (eval_type IN ('AND_OR', 'AND', 'OR', 'CUSTOM')),
    CONSTRAINT ck_action_escalation_period CHECK (escalation_period_seconds >= 60)
);

CREATE TABLE action_condition (
    condition_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_id       BIGINT       NOT NULL REFERENCES action(action_id) ON DELETE CASCADE,
    -- Single-letter label referenced by action.formula.
    label           VARCHAR(8)   NOT NULL DEFAULT 'A',
    condition_type  VARCHAR(32)  NOT NULL,
    operator        VARCHAR(24)  NOT NULL DEFAULT 'EQUALS',
    value           VARCHAR(2048) NOT NULL DEFAULT '',
    -- Second value, used by tag-value conditions where value holds the tag.
    value2          VARCHAR(255) NOT NULL DEFAULT '',
    CONSTRAINT ck_action_condition_type CHECK (condition_type IN
        ('HOST_GROUP', 'HOST', 'TRIGGER', 'TRIGGER_NAME', 'TRIGGER_SEVERITY',
         'TIME_PERIOD', 'HOST_TEMPLATE', 'PROBLEM_SUPPRESSED', 'EVENT_TAG',
         'EVENT_TAG_VALUE', 'HOST_CLASS', 'PROXY')),
    CONSTRAINT ck_action_condition_op CHECK (operator IN
        ('EQUALS', 'NOT_EQUALS', 'CONTAINS', 'NOT_CONTAINS', 'IN', 'NOT_IN',
         'GREATER_OR_EQUAL', 'LESS_OR_EQUAL', 'MATCHES', 'NOT_MATCHES', 'YES', 'NO'))
);

CREATE INDEX ix_action_condition_action ON action_condition (action_id);

-- One rung of an escalation ladder.
CREATE TABLE action_operation (
    operation_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_id       BIGINT       NOT NULL REFERENCES action(action_id) ON DELETE CASCADE,
    operation_type  VARCHAR(32)  NOT NULL DEFAULT 'SEND_MESSAGE',
    -- Escalation step range this operation covers. step_to = 0 means "from
    -- step_from onwards, forever", which is how a final on-call rung is built.
    step_from       INTEGER      NOT NULL DEFAULT 1,
    step_to         INTEGER      NOT NULL DEFAULT 1,
    -- Overrides action.escalation_period_seconds for this rung; 0 inherits.
    step_duration_seconds INTEGER NOT NULL DEFAULT 0,
    -- Only escalate this rung when the problem is still unacknowledged.
    eval_type       VARCHAR(16)  NOT NULL DEFAULT 'AND_OR',
    -- Targets: explicit users and/or whole user groups.
    media_type_id   BIGINT       REFERENCES media_type(media_type_id) ON DELETE SET NULL,
    -- Remote command / script operations.
    command         TEXT         NOT NULL DEFAULT '',
    command_target  VARCHAR(24)  NOT NULL DEFAULT 'CURRENT_HOST',
    -- Custom message overriding the media type template.
    custom_message  BOOLEAN      NOT NULL DEFAULT FALSE,
    subject         VARCHAR(1024) NOT NULL DEFAULT '',
    message         TEXT         NOT NULL DEFAULT '',
    CONSTRAINT ck_operation_type CHECK (operation_type IN
        ('SEND_MESSAGE', 'REMOTE_COMMAND', 'ADD_HOST', 'REMOVE_HOST', 'ENABLE_HOST',
         'DISABLE_HOST', 'ADD_TO_GROUP', 'REMOVE_FROM_GROUP', 'LINK_TEMPLATE',
         'UNLINK_TEMPLATE', 'SET_HOST_INVENTORY_MODE', 'WEBHOOK')),
    CONSTRAINT ck_operation_steps CHECK (step_from >= 1 AND (step_to = 0 OR step_to >= step_from))
);

CREATE INDEX ix_action_operation_action ON action_operation (action_id);

CREATE TABLE action_operation_user (
    operation_id    BIGINT NOT NULL REFERENCES action_operation(operation_id) ON DELETE CASCADE,
    user_id         BIGINT NOT NULL REFERENCES app_user(user_id) ON DELETE CASCADE,
    PRIMARY KEY (operation_id, user_id)
);

CREATE TABLE action_operation_group (
    operation_id    BIGINT NOT NULL REFERENCES action_operation(operation_id) ON DELETE CASCADE,
    usrgrp_id       BIGINT NOT NULL REFERENCES user_group(usrgrp_id) ON DELETE CASCADE,
    PRIMARY KEY (operation_id, usrgrp_id)
);

-- ---------------------------------------------------------------------------
-- Escalations and alerts
--
-- An escalation is the live state machine for one (action, problem) pair.
-- An alert is a single delivery attempt produced by it.
-- ---------------------------------------------------------------------------

CREATE TABLE escalation (
    escalation_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT       NOT NULL REFERENCES tenant(tenant_id) ON DELETE CASCADE,
    action_id       BIGINT       NOT NULL REFERENCES action(action_id) ON DELETE CASCADE,
    problem_id      BIGINT       NOT NULL REFERENCES problem(problem_id) ON DELETE CASCADE,
    trigger_id      BIGINT,
    host_id         BIGINT       REFERENCES host(host_id) ON DELETE CASCADE,
    step            INTEGER      NOT NULL DEFAULT 0,
    status          VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    next_run_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    -- One escalation per action per problem; the unique constraint is what
    -- makes concurrent event processing safe.
    CONSTRAINT uq_escalation UNIQUE (action_id, problem_id),
    CONSTRAINT ck_escalation_status CHECK (status IN
        ('ACTIVE', 'PAUSED_MAINTENANCE', 'PAUSED_ACK', 'RECOVERING', 'COMPLETED', 'CANCELLED'))
);

-- The escalator's hot query.
CREATE INDEX ix_escalation_due ON escalation (next_run_at)
    WHERE status IN ('ACTIVE', 'RECOVERING');
CREATE INDEX ix_escalation_problem ON escalation (problem_id);

CREATE TABLE alert (
    alert_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT       NOT NULL REFERENCES tenant(tenant_id) ON DELETE CASCADE,
    action_id       BIGINT       REFERENCES action(action_id) ON DELETE SET NULL,
    escalation_id   BIGINT       REFERENCES escalation(escalation_id) ON DELETE SET NULL,
    problem_id      BIGINT       REFERENCES problem(problem_id) ON DELETE CASCADE,
    event_id        BIGINT       REFERENCES event(event_id) ON DELETE SET NULL,
    user_id         BIGINT       REFERENCES app_user(user_id) ON DELETE SET NULL,
    media_type_id   BIGINT       REFERENCES media_type(media_type_id) ON DELETE SET NULL,
    alert_type      VARCHAR(16)  NOT NULL DEFAULT 'MESSAGE',
    send_to         VARCHAR(1024) NOT NULL DEFAULT '',
    subject         VARCHAR(1024) NOT NULL DEFAULT '',
    message         TEXT         NOT NULL DEFAULT '',
    status          VARCHAR(16)  NOT NULL DEFAULT 'NEW',
    retries         INTEGER      NOT NULL DEFAULT 0,
    error           TEXT         NOT NULL DEFAULT '',
    escalation_step INTEGER      NOT NULL DEFAULT 0,
    scheduled_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    sent_at         TIMESTAMPTZ,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_alert_type CHECK (alert_type IN ('MESSAGE', 'REMOTE_COMMAND')),
    CONSTRAINT ck_alert_status CHECK (status IN ('NEW', 'SENDING', 'SENT', 'FAILED', 'CANCELLED'))
);

-- The sender's hot query: due, not yet delivered.
CREATE INDEX ix_alert_pending ON alert (scheduled_at)
    WHERE status IN ('NEW', 'SENDING');
CREATE INDEX ix_alert_problem ON alert (problem_id, created_at DESC);
CREATE INDEX ix_alert_history ON alert (tenant_id, created_at DESC);

-- ---------------------------------------------------------------------------
-- Maintenance windows
-- ---------------------------------------------------------------------------

CREATE TABLE maintenance (
    maintenance_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT       NOT NULL REFERENCES tenant(tenant_id) ON DELETE CASCADE,
    name            VARCHAR(255) NOT NULL,
    -- WITH_DATA still collects metrics but suppresses problems; WITHOUT_DATA
    -- stops collection entirely. The distinction matters for capacity reports
    -- that should not have holes punched in them by a reboot window.
    maintenance_type VARCHAR(24) NOT NULL DEFAULT 'WITH_DATA',
    active_since    TIMESTAMPTZ  NOT NULL,
    active_till     TIMESTAMPTZ  NOT NULL,
    -- Only suppress problems whose tags match, so a "disk" maintenance does
    -- not silence a security alert on the same host.
    tags_eval_type  VARCHAR(16)  NOT NULL DEFAULT 'AND_OR',
    description     TEXT         NOT NULL DEFAULT '',
    CONSTRAINT uq_maintenance_name UNIQUE (tenant_id, name),
    CONSTRAINT ck_maintenance_type CHECK (maintenance_type IN ('WITH_DATA', 'WITHOUT_DATA')),
    CONSTRAINT ck_maintenance_window CHECK (active_till > active_since)
);

CREATE TABLE maintenance_period (
    period_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    maintenance_id  BIGINT       NOT NULL REFERENCES maintenance(maintenance_id) ON DELETE CASCADE,
    period_type     VARCHAR(16)  NOT NULL DEFAULT 'ONE_TIME',
    start_date      TIMESTAMPTZ,
    -- Seconds past midnight for recurring periods.
    start_time_seconds INTEGER   NOT NULL DEFAULT 0,
    duration_seconds INTEGER     NOT NULL DEFAULT 3600,
    every           INTEGER      NOT NULL DEFAULT 1,
    -- Bit mask, Monday = 1.
    day_of_week     INTEGER      NOT NULL DEFAULT 0,
    day_of_month    INTEGER      NOT NULL DEFAULT 0,
    month           INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT ck_period_type CHECK (period_type IN ('ONE_TIME', 'DAILY', 'WEEKLY', 'MONTHLY')),
    CONSTRAINT ck_period_duration CHECK (duration_seconds > 0)
);

CREATE TABLE maintenance_host (
    maintenance_id  BIGINT NOT NULL REFERENCES maintenance(maintenance_id) ON DELETE CASCADE,
    host_id         BIGINT NOT NULL REFERENCES host(host_id) ON DELETE CASCADE,
    PRIMARY KEY (maintenance_id, host_id)
);

CREATE TABLE maintenance_group (
    maintenance_id  BIGINT NOT NULL REFERENCES maintenance(maintenance_id) ON DELETE CASCADE,
    group_id        BIGINT NOT NULL REFERENCES host_group(group_id) ON DELETE CASCADE,
    PRIMARY KEY (maintenance_id, group_id)
);

CREATE TABLE maintenance_tag (
    tag_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    maintenance_id  BIGINT       NOT NULL REFERENCES maintenance(maintenance_id) ON DELETE CASCADE,
    tag             VARCHAR(255) NOT NULL,
    operator        VARCHAR(16)  NOT NULL DEFAULT 'EQUALS',
    value           VARCHAR(255) NOT NULL DEFAULT ''
);

-- ---------------------------------------------------------------------------
-- Discovery
--
-- Network discovery finds hosts on a subnet. Low-level discovery (LLD) finds
-- entities *inside* a known host: interfaces, filesystems, camera channels.
-- ---------------------------------------------------------------------------

CREATE TABLE discovery_rule (
    drule_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT       NOT NULL REFERENCES tenant(tenant_id) ON DELETE CASCADE,
    name            VARCHAR(255) NOT NULL,
    proxy_id        BIGINT       REFERENCES proxy(proxy_id) ON DELETE SET NULL,
    -- Comma-separated ranges: "10.0.0.1-254, 192.168.1.0/24".
    ip_range        VARCHAR(2048) NOT NULL,
    delay_seconds   INTEGER      NOT NULL DEFAULT 3600,
    status          VARCHAR(16)  NOT NULL DEFAULT 'ENABLED',
    concurrency     INTEGER      NOT NULL DEFAULT 32,
    next_run_at     TIMESTAMPTZ,
    CONSTRAINT uq_drule_name UNIQUE (tenant_id, name),
    CONSTRAINT ck_drule_status CHECK (status IN ('ENABLED', 'DISABLED'))
);

-- One probe performed against each address in the range.
CREATE TABLE discovery_check (
    dcheck_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drule_id        BIGINT       NOT NULL REFERENCES discovery_rule(drule_id) ON DELETE CASCADE,
    check_type      VARCHAR(32)  NOT NULL,
    ports           VARCHAR(255) NOT NULL DEFAULT '',
    key_            VARCHAR(2048) NOT NULL DEFAULT '',
    params          JSONB        NOT NULL DEFAULT '{}'::jsonb,
    -- Use this check's returned value as the discovered host's name / IP.
    uniq            BOOLEAN      NOT NULL DEFAULT FALSE,
    host_source     BOOLEAN      NOT NULL DEFAULT FALSE,
    name_source     BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE TABLE discovered_host (
    dhost_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drule_id        BIGINT       NOT NULL REFERENCES discovery_rule(drule_id) ON DELETE CASCADE,
    ip              VARCHAR(64)  NOT NULL,
    dns             VARCHAR(255) NOT NULL DEFAULT '',
    status          VARCHAR(16)  NOT NULL DEFAULT 'UP',
    first_seen_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    last_seen_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    last_down_at    TIMESTAMPTZ,
    -- Values returned by each discovery check, used for classification.
    check_results   JSONB        NOT NULL DEFAULT '{}'::jsonb,
    host_id         BIGINT       REFERENCES host(host_id) ON DELETE SET NULL,
    CONSTRAINT uq_discovered_host UNIQUE (drule_id, ip),
    CONSTRAINT ck_dhost_status CHECK (status IN ('UP', 'DOWN'))
);

CREATE INDEX ix_discovered_host_rule ON discovered_host (drule_id, status);

-- Low-level discovery: an item whose value is a JSON array of entities, each
-- turned into real items/triggers by substituting LLD macros into prototypes.
CREATE TABLE lld_discovered_entity (
    entity_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lld_item_id     BIGINT       NOT NULL REFERENCES item(item_id) ON DELETE CASCADE,
    -- Stable identity of the discovered entity, derived from its LLD macros.
    entity_key      VARCHAR(512) NOT NULL,
    macros          JSONB        NOT NULL DEFAULT '{}'::jsonb,
    first_seen_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    last_seen_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    -- Set when the entity stops being reported; the objects it created are
    -- removed once the rule's lifetime elapses.
    lost_at         TIMESTAMPTZ,
    CONSTRAINT uq_lld_entity UNIQUE (lld_item_id, entity_key)
);

-- Filters restricting which discovered entities produce objects.
CREATE TABLE lld_filter (
    filter_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lld_item_id     BIGINT       NOT NULL REFERENCES item(item_id) ON DELETE CASCADE,
    macro           VARCHAR(255) NOT NULL,
    operator        VARCHAR(16)  NOT NULL DEFAULT 'MATCHES',
    value           VARCHAR(2048) NOT NULL DEFAULT '',
    CONSTRAINT ck_lld_filter_op CHECK (operator IN ('MATCHES', 'NOT_MATCHES', 'EXISTS', 'NOT_EXISTS'))
);

-- Hosts may register themselves on first contact rather than be pre-created.
CREATE TABLE autoreg_host (
    autoreg_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT       NOT NULL REFERENCES tenant(tenant_id) ON DELETE CASCADE,
    host            VARCHAR(255) NOT NULL,
    host_metadata   TEXT         NOT NULL DEFAULT '',
    ip              VARCHAR(64)  NOT NULL DEFAULT '',
    dns             VARCHAR(255) NOT NULL DEFAULT '',
    port            INTEGER      NOT NULL DEFAULT 10150,
    proxy_id        BIGINT       REFERENCES proxy(proxy_id) ON DELETE SET NULL,
    first_seen_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    last_seen_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    host_id         BIGINT       REFERENCES host(host_id) ON DELETE SET NULL,
    CONSTRAINT uq_autoreg_host UNIQUE (tenant_id, host)
);

-- ---------------------------------------------------------------------------
-- Presentation: dashboards, graphs, maps
-- ---------------------------------------------------------------------------

CREATE TABLE dashboard (
    dashboard_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT       NOT NULL REFERENCES tenant(tenant_id) ON DELETE CASCADE,
    name            VARCHAR(255) NOT NULL,
    owner_user_id   BIGINT       REFERENCES app_user(user_id) ON DELETE SET NULL,
    private         BOOLEAN      NOT NULL DEFAULT TRUE,
    auto_refresh_seconds INTEGER NOT NULL DEFAULT 30,
    display_period_seconds INTEGER NOT NULL DEFAULT 30,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE dashboard_widget (
    widget_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dashboard_id    BIGINT       NOT NULL REFERENCES dashboard(dashboard_id) ON DELETE CASCADE,
    type            VARCHAR(32)  NOT NULL,
    name            VARCHAR(255) NOT NULL DEFAULT '',
    -- Grid position, 24 columns wide.
    pos_x           INTEGER      NOT NULL DEFAULT 0,
    pos_y           INTEGER      NOT NULL DEFAULT 0,
    width           INTEGER      NOT NULL DEFAULT 12,
    height          INTEGER      NOT NULL DEFAULT 5,
    config          JSONB        NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT ck_widget_type CHECK (type IN
        ('PROBLEMS', 'PROBLEM_SEVERITY', 'GRAPH', 'SVG_GRAPH', 'GAUGE', 'ITEM_VALUE',
         'CLOCK', 'MAP', 'HOST_AVAILABILITY', 'SYSTEM_INFO', 'TOP_HOSTS', 'URL',
         'CAMERA_WALL', 'DISCOVERY_STATUS', 'ACTION_LOG', 'DATA_OVERVIEW')),
    CONSTRAINT ck_widget_geometry CHECK (width > 0 AND height > 0 AND pos_x >= 0 AND pos_y >= 0)
);

CREATE INDEX ix_widget_dashboard ON dashboard_widget (dashboard_id);

CREATE TABLE graph (
    graph_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT       NOT NULL REFERENCES tenant(tenant_id) ON DELETE CASCADE,
    name            VARCHAR(255) NOT NULL,
    width           INTEGER      NOT NULL DEFAULT 900,
    height          INTEGER      NOT NULL DEFAULT 200,
    graph_type      VARCHAR(16)  NOT NULL DEFAULT 'NORMAL',
    show_legend     BOOLEAN      NOT NULL DEFAULT TRUE,
    show_working_time BOOLEAN    NOT NULL DEFAULT TRUE,
    y_axis_min      DOUBLE PRECISION,
    y_axis_max      DOUBLE PRECISION,
    percent_left    DOUBLE PRECISION,
    percent_right   DOUBLE PRECISION,
    flags           VARCHAR(16)  NOT NULL DEFAULT 'NORMAL',
    CONSTRAINT ck_graph_type CHECK (graph_type IN ('NORMAL', 'STACKED', 'PIE', 'EXPLODED')),
    CONSTRAINT ck_graph_flags CHECK (flags IN ('NORMAL', 'PROTOTYPE', 'DISCOVERED'))
);

CREATE TABLE graph_item (
    gitem_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    graph_id        BIGINT       NOT NULL REFERENCES graph(graph_id) ON DELETE CASCADE,
    item_id         BIGINT       NOT NULL REFERENCES item(item_id) ON DELETE CASCADE,
    sortorder       INTEGER      NOT NULL DEFAULT 0,
    color           VARCHAR(8)   NOT NULL DEFAULT '1A7C11',
    draw_type       VARCHAR(16)  NOT NULL DEFAULT 'LINE',
    y_axis_side     VARCHAR(8)   NOT NULL DEFAULT 'LEFT',
    calc_function   VARCHAR(16)  NOT NULL DEFAULT 'AVG',
    CONSTRAINT ck_gitem_draw CHECK (draw_type IN ('LINE', 'FILLED', 'BOLD_LINE', 'DOT', 'DASHED', 'GRADIENT')),
    CONSTRAINT ck_gitem_axis CHECK (y_axis_side IN ('LEFT', 'RIGHT')),
    CONSTRAINT ck_gitem_calc CHECK (calc_function IN ('MIN', 'AVG', 'MAX', 'ALL', 'LAST'))
);

CREATE INDEX ix_graph_item_graph ON graph_item (graph_id);

-- Network topology maps.
CREATE TABLE network_map (
    map_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT       NOT NULL REFERENCES tenant(tenant_id) ON DELETE CASCADE,
    name            VARCHAR(255) NOT NULL,
    width           INTEGER      NOT NULL DEFAULT 1200,
    height          INTEGER      NOT NULL DEFAULT 800,
    background_url  VARCHAR(2048) NOT NULL DEFAULT '',
    owner_user_id   BIGINT       REFERENCES app_user(user_id) ON DELETE SET NULL,
    private         BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_map_name UNIQUE (tenant_id, name)
);

CREATE TABLE network_map_element (
    element_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    map_id          BIGINT       NOT NULL REFERENCES network_map(map_id) ON DELETE CASCADE,
    element_type    VARCHAR(16)  NOT NULL DEFAULT 'HOST',
    -- Points at a host, host group, map or trigger depending on element_type.
    element_ref_id  BIGINT,
    label           VARCHAR(2048) NOT NULL DEFAULT '',
    x               INTEGER      NOT NULL DEFAULT 0,
    y               INTEGER      NOT NULL DEFAULT 0,
    icon            VARCHAR(64)  NOT NULL DEFAULT 'server',
    url             VARCHAR(2048) NOT NULL DEFAULT '',
    CONSTRAINT ck_map_element_type CHECK (element_type IN ('HOST', 'HOST_GROUP', 'TRIGGER', 'MAP', 'IMAGE'))
);

CREATE TABLE network_map_link (
    link_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    map_id          BIGINT       NOT NULL REFERENCES network_map(map_id) ON DELETE CASCADE,
    from_element_id BIGINT       NOT NULL REFERENCES network_map_element(element_id) ON DELETE CASCADE,
    to_element_id   BIGINT       NOT NULL REFERENCES network_map_element(element_id) ON DELETE CASCADE,
    label           VARCHAR(2048) NOT NULL DEFAULT '',
    color           VARCHAR(8)   NOT NULL DEFAULT '00CC00',
    draw_type       VARCHAR(16)  NOT NULL DEFAULT 'LINE',
    -- When any of these triggers is in PROBLEM the link is drawn in its colour,
    -- which is what makes a map convey state rather than just topology.
    indicator_trigger_ids BIGINT[] NOT NULL DEFAULT '{}'
);

-- ---------------------------------------------------------------------------
-- Audit
-- ---------------------------------------------------------------------------

CREATE TABLE audit_log (
    audit_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT       NOT NULL REFERENCES tenant(tenant_id) ON DELETE CASCADE,
    clock           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    user_id         BIGINT,
    username        VARCHAR(128) NOT NULL DEFAULT '',
    ip              VARCHAR(64)  NOT NULL DEFAULT '',
    action          VARCHAR(24)  NOT NULL,
    resource_type   VARCHAR(48)  NOT NULL,
    resource_id     BIGINT,
    resource_name   VARCHAR(255) NOT NULL DEFAULT '',
    -- Field-level before/after, so a config regression can be traced to a
    -- person and a timestamp.
    details         JSONB        NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT ck_audit_action CHECK (action IN
        ('LOGIN', 'LOGOUT', 'LOGIN_FAILED', 'CREATE', 'UPDATE', 'DELETE', 'EXECUTE', 'ACKNOWLEDGE'))
);

CREATE INDEX ix_audit_clock ON audit_log (tenant_id, clock DESC);
CREATE INDEX ix_audit_resource ON audit_log (resource_type, resource_id, clock DESC);
